# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'it52app' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for it52app
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'

  target 'it52appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pre_install do |installer|
 # copied from https://github.com/CocoaPods/CocoaPods/issues/2926
 # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
 def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|
  	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
      		config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
    	end
  	end
end